import type { Metadata } from "next";
import { Inter, Forum } from "next/font/google";
import "./globals.css";
import Navbar from "../components/User/Navbar/Navbar";
import Hero from "../components/User/Hero/Hero";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import Footer from "../components/User/Footer/Footer";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const forum = Forum({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-forum",
});

export const metadata: Metadata = {
  title: "Borport",
  description: "Generated by create next app",
  icons: {
    icon: "Borportmobile.png",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: string;
  };
}

async function getMessages(locale: string) {
  try {
    return (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  const messages = await getMessages(locale);
  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${forum.variable}`}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          {children}
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
